common: &shared
    adapter: mysql2
    encoding: utf8
    username: humbroll 
    password: tkddlf 
    socket: /tmp/mysql.sock    
    # host: 175.158.14.24

development:
    database: appdata_development
    <<: *shared

test:
    database: appdata_test
    <<: *shared

production:
    database: appdata_production
    <<: *shared

##add user 
# use mysql;
# GRANT USAGE ON *.* TO humbroll@localhost IDENTIFIED BY "wjdtkd1";
# GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER ON appdata_development.* TO humbroll@localhost;
# GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER ON appdata_test.* TO humbroll@localhost;
# GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER ON appdata_production.* TO humbroll@localhost;
# flush privileges;

